USE [master]
GO

/****** Object:  Database [QLSV]    Script Date: 3/25/2025 9:42:04 PM ******/
CREATE DATABASE [QLSV]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLSV', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\QLSV.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLSV_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\QLSV_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLSV].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QLSV] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QLSV] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QLSV] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QLSV] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QLSV] SET ARITHABORT OFF 
GO

ALTER DATABASE [QLSV] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QLSV] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QLSV] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QLSV] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QLSV] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QLSV] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QLSV] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QLSV] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QLSV] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QLSV] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QLSV] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QLSV] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QLSV] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QLSV] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QLSV] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QLSV] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QLSV] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QLSV] SET RECOVERY FULL 
GO

ALTER DATABASE [QLSV] SET  MULTI_USER 
GO

ALTER DATABASE [QLSV] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QLSV] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QLSV] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QLSV] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QLSV] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QLSV] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QLSV] SET QUERY_STORE = ON
GO

ALTER DATABASE [QLSV] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [QLSV] SET  READ_WRITE 
GO

USE [QLSV]
GO

/****** Object:  Table [dbo].[BoMon]    Script Date: 3/25/2025 9:42:28 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BoMon](
	[mabm] [nvarchar](20) NOT NULL,
	[tenbm] [nvarchar](50) NULL,
	[makhoa] [nvarchar](20) NULL,
 CONSTRAINT [PK_boMon] PRIMARY KEY CLUSTERED 
(
	[mabm] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BoMon]  WITH CHECK ADD  CONSTRAINT [FK_BoMon_MaKhoa] FOREIGN KEY([makhoa])
REFERENCES [dbo].[Khoa] ([makhoa])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[BoMon] CHECK CONSTRAINT [FK_BoMon_MaKhoa]
GO

USE [QLSV]
GO

/****** Object:  Table [dbo].[DKMH]    Script Date: 3/25/2025 9:42:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DKMH](
	[malophp] [nvarchar](20) NOT NULL,
	[masv] [nvarchar](13) NOT NULL,
	[diemtp] [float] NULL,
	[diemthi] [float] NULL,
	[phantramthi] [float] NULL,
 CONSTRAINT [PK_DKMH] PRIMARY KEY CLUSTERED 
(
	[malophp] ASC,
	[masv] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DKMH]  WITH CHECK ADD  CONSTRAINT [FK_DKMH_MaLopHP] FOREIGN KEY([malophp])
REFERENCES [dbo].[LopHP] ([malophp])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[DKMH] CHECK CONSTRAINT [FK_DKMH_MaLopHP]
GO

ALTER TABLE [dbo].[DKMH]  WITH CHECK ADD  CONSTRAINT [FK_DKMH_MaSV] FOREIGN KEY([masv])
REFERENCES [dbo].[SinhVien] ([masv])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[DKMH] CHECK CONSTRAINT [FK_DKMH_MaSV]
GO

ALTER TABLE [dbo].[DKMH]  WITH CHECK ADD  CONSTRAINT [CK_DKMH_DiemThi] CHECK  (([diemthi]>=(0) AND [diemthi]<=(10)))
GO

ALTER TABLE [dbo].[DKMH] CHECK CONSTRAINT [CK_DKMH_DiemThi]
GO

ALTER TABLE [dbo].[DKMH]  WITH CHECK ADD  CONSTRAINT [CK_DKMH_DiemTP] CHECK  (([diemtp]<=(10) AND [diemtp]>=(0)))
GO

ALTER TABLE [dbo].[DKMH] CHECK CONSTRAINT [CK_DKMH_DiemTP]
GO

USE [QLSV]
GO

/****** Object:  Table [dbo].[GiaoVien]    Script Date: 3/25/2025 9:43:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GiaoVien](
	[magv] [nvarchar](20) NOT NULL,
	[hoten] [nvarchar](50) NULL,
	[ngaysinh] [date] NULL,
	[mabm] [nvarchar](20) NULL,
 CONSTRAINT [PK_GiaoVien] PRIMARY KEY CLUSTERED 
(
	[magv] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GiaoVien]  WITH CHECK ADD  CONSTRAINT [FK_GiaoVien_MaBoMon] FOREIGN KEY([mabm])
REFERENCES [dbo].[BoMon] ([mabm])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[GiaoVien] CHECK CONSTRAINT [FK_GiaoVien_MaBoMon]
GO

USE [QLSV]
GO

/****** Object:  Table [dbo].[GVCN]    Script Date: 3/25/2025 9:43:30 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GVCN](
	[malop] [nvarchar](20) NOT NULL,
	[magv] [nvarchar](20) NOT NULL,
	[HK] [float] NOT NULL,
 CONSTRAINT [PK_GVCN] PRIMARY KEY CLUSTERED 
(
	[malop] ASC,
	[magv] ASC,
	[HK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GVCN]  WITH CHECK ADD  CONSTRAINT [FK_GVCN_MaGV] FOREIGN KEY([magv])
REFERENCES [dbo].[GiaoVien] ([magv])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[GVCN] CHECK CONSTRAINT [FK_GVCN_MaGV]
GO

ALTER TABLE [dbo].[GVCN]  WITH CHECK ADD  CONSTRAINT [FK_GVCN_MaLop] FOREIGN KEY([malop])
REFERENCES [dbo].[Lop] ([malop])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[GVCN] CHECK CONSTRAINT [FK_GVCN_MaLop]
GO

USE [QLSV]
GO

/****** Object:  Table [dbo].[Khoa]    Script Date: 3/25/2025 9:43:42 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Khoa](
	[makhoa] [nvarchar](20) NOT NULL,
	[tenkhoa] [nvarchar](50) NULL,
 CONSTRAINT [PK_Khoa] PRIMARY KEY CLUSTERED 
(
	[makhoa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [QLSV]
GO

/****** Object:  Table [dbo].[Lop]    Script Date: 3/25/2025 9:43:54 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Lop](
	[malop] [nvarchar](20) NOT NULL,
	[tenlop] [nvarchar](50) NULL,
 CONSTRAINT [PK_Lop] PRIMARY KEY CLUSTERED 
(
	[malop] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [QLSV]
GO

/****** Object:  Table [dbo].[LopHP]    Script Date: 3/25/2025 9:44:06 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LopHP](
	[malophp] [nvarchar](20) NOT NULL,
	[tenlophp] [nvarchar](50) NULL,
	[HK] [float] NULL,
	[mamon] [nvarchar](20) NULL,
	[magv] [nvarchar](20) NULL,
 CONSTRAINT [PK_LopHP] PRIMARY KEY CLUSTERED 
(
	[malophp] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LopHP]  WITH CHECK ADD  CONSTRAINT [FK_LopHP_GiaoVien] FOREIGN KEY([magv])
REFERENCES [dbo].[GiaoVien] ([magv])
GO

ALTER TABLE [dbo].[LopHP] CHECK CONSTRAINT [FK_LopHP_GiaoVien]
GO

ALTER TABLE [dbo].[LopHP]  WITH CHECK ADD  CONSTRAINT [FK_LopHP_MaMon] FOREIGN KEY([mamon])
REFERENCES [dbo].[MonHoc] ([mamon])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[LopHP] CHECK CONSTRAINT [FK_LopHP_MaMon]
GO

USE [QLSV]
GO

/****** Object:  Table [dbo].[LopSV]    Script Date: 3/25/2025 9:44:21 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LopSV](
	[malop] [nvarchar](20) NOT NULL,
	[masv] [nvarchar](13) NOT NULL,
	[chucvu] [nvarchar](20) NULL,
 CONSTRAINT [PK_LopSV] PRIMARY KEY CLUSTERED 
(
	[malop] ASC,
	[masv] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LopSV]  WITH CHECK ADD  CONSTRAINT [FK_LopSV_MaLop] FOREIGN KEY([malop])
REFERENCES [dbo].[Lop] ([malop])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[LopSV] CHECK CONSTRAINT [FK_LopSV_MaLop]
GO

ALTER TABLE [dbo].[LopSV]  WITH CHECK ADD  CONSTRAINT [FK_LopSV_MaSV] FOREIGN KEY([masv])
REFERENCES [dbo].[SinhVien] ([masv])
GO

ALTER TABLE [dbo].[LopSV] CHECK CONSTRAINT [FK_LopSV_MaSV]
GO

USE [QLSV]
GO

/****** Object:  Table [dbo].[MonHoc]    Script Date: 3/25/2025 9:44:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MonHoc](
	[mamon] [nvarchar](20) NOT NULL,
	[tenmon] [nvarchar](50) NULL,
	[stc] [float] NULL,
 CONSTRAINT [PK_MonHoc] PRIMARY KEY CLUSTERED 
(
	[mamon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MonHoc]  WITH CHECK ADD  CONSTRAINT [CK_MonHoc_stc] CHECK  (([stc]<=(3) AND [stc]>=(1)))
GO

ALTER TABLE [dbo].[MonHoc] CHECK CONSTRAINT [CK_MonHoc_stc]
GO

USE [QLSV]
GO

/****** Object:  Table [dbo].[SinhVien]    Script Date: 3/25/2025 9:44:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SinhVien](
	[masv] [nvarchar](13) NOT NULL,
	[hoten] [nvarchar](50) NULL,
	[ngaysinh] [date] NULL,
 CONSTRAINT [PK_SinhVien] PRIMARY KEY CLUSTERED 
(
	[masv] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
